### ISSUE TITLE
Practica 1

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-recyclanexus#3]
[PRACTICA1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-recyclanexus/files/14315603/PRACTICA1.pdf)

**Comment by Elisahadad** [comment]
18 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
